name: Container build - Push action
on:
  push:
      branches:
        - master
        - develop
        - miesh-v1

jobs:
  build-container:
    name: Build Backend and Frontend Containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      SKIP_RABBIT_MQ: true

    steps:
      - name: Wait on check
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.sha }}
          check-name: 'Integration test for Cenit'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Branch Names
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: Short SHA
        id: short-sha
        uses: benjlevesque/short-sha@v1.2

      - name: Build and push backend image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cenit
          registry: ghcr.io
          tags: backend-${{ steps.branch-name.outputs.current_branch }}-${{ steps.short-sha.outputs.sha }}
          dockerfile: docker/ubuntu/Dockerfile
          buildArgs: "BRANCH=${{ steps.branch-name.outputs.current_branch }}"

      - name: Build and push frontend image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: cenit
          registry: ghcr.io
          tags: frontend-${{ steps.branch-name.outputs.current_branch }}-${{ steps.short-sha.outputs.sha }}
          dockerfile: docker/ubuntu/ui/Dockerfile
          buildArgs: "BRANCH=${{ steps.branch-name.outputs.current_branch }}, COMMIT=${{ steps.short-sha.outputs.sha }}"
